import { CARD_TYPES, OFF_AFFINITY_EFFECT_MULTIPLIER, SEGMENT_TAGS } from './constants.js';
import { getCard } from './cards.js';

function onAffinity(card, segment) { return card.affinity.includes('any') || card.affinity.some((tag) => segment.tags.includes(tag)); }
function estimatedCones(card, segment, vehicle, flow, affinity, tirePenalty = 0) { const margin = (card.control ?? 0) + (vehicle.handlingProfile?.controlBonus ?? 0) + (flow > 0 ? 1 : 0) + (affinity ? 1 : 0) - segment.precision - tirePenalty; if (margin < -4) return 2; if (margin < -2) return 1; return 0; }
function lineScore(instance, state, segment, mode) { const card = getCard(instance.cardId); const affinity = onAffinity(card, segment); const effect = card.timeDelta * (affinity ? 1 : OFF_AFFINITY_EFFECT_MULTIPLIER); const tirePenalty = state.passives.controlPenaltyOnPrecision && segment.tags.includes(SEGMENT_TAGS.PRECISION) ? state.passives.controlPenaltyOnPrecision : 0; const cones = estimatedCones(card, segment, state.vehicle, state.flow, affinity, tirePenalty); const wear = Object.values(card.wear ?? {}).reduce((sum, value) => sum + value, 0); const strain = card.effect?.addStrainToHand ?? 0; if (mode === 'aggression') return (card.type === CARD_TYPES.AGGRESSION ? -20 : 0) + effect + cones * 2 + wear * 0.01; if (mode === 'clean') return effect + cones * 6 + wear * 0.08 + strain * 1.2 - (card.control ?? 0) * 0.15; return effect + cones * 3 + wear * 0.06 + strain * 0.65 - (affinity ? 0.2 : 0); }
function chooseLowest(items, score) { return items.length ? [...items].sort((a, b) => score(a) - score(b))[0] : null; }
function chooseUtilityCommon({ hand, segment }, mode) { const strain = hand.find((item) => item.cardId === 'unsettled'); const count = hand.filter((item) => item.cardId === 'unsettled').length; if (strain && (count >= 2 || mode === 'clean')) return strain.instanceId; const grip = hand.find((item) => item.cardId === 'grip-window'); if (grip && segment.tags.some((tag) => ['tight', 'flowing', 'transition', 'precision'].includes(tag))) return grip.instanceId; const eyes = hand.find((item) => item.cardId === 'eyes-up'); const playable = hand.filter((item) => [CARD_TYPES.TECHNIQUE, CARD_TYPES.AGGRESSION].includes(getCard(item.cardId).type)).length; if (eyes && (playable <= 2 || mode === 'balanced')) return eyes.instanceId; return null; }
function chooseDiscardCommon({ hand }) { return hand.find((item) => item.cardId === 'unsettled')?.instanceId ?? hand.find((item) => getCard(item.cardId).type === CARD_TYPES.HAZARD)?.instanceId ?? hand[0]?.instanceId ?? null; }
function createStrategicBot(mode) { return { name: mode, chooseMulligan({ hand, course }) { const first = course[0]; const playable = hand.filter((item) => [CARD_TYPES.TECHNIQUE, CARD_TYPES.AGGRESSION].includes(getCard(item.cardId).type)); if (playable.some((item) => onAffinity(getCard(item.cardId), first))) return null; return hand.find((item) => !playable.includes(item))?.instanceId ?? playable[0]?.instanceId ?? null; }, chooseUtility(context) { return chooseUtilityCommon(context, mode); }, chooseDiscard: chooseDiscardCommon, chooseLine({ state, segment, playable }) { return chooseLowest(playable, (item) => lineScore(item, state, segment, mode))?.instanceId ?? null; } }; }

export const balancedBot = createStrategicBot('balanced');
export const cleanBot = createStrategicBot('clean');
export const aggressionBot = createStrategicBot('aggression');
export const affinityBot = { name: 'affinity', chooseMulligan({ hand, course }) { return hand.find((item) => { const card = getCard(item.cardId); return [CARD_TYPES.TECHNIQUE, CARD_TYPES.AGGRESSION].includes(card.type) && !onAffinity(card, course[0]); })?.instanceId ?? null; }, chooseUtility(context) { return chooseUtilityCommon(context, 'balanced'); }, chooseDiscard: chooseDiscardCommon, chooseLine({ state, segment, playable }) { const affinity = playable.filter((item) => onAffinity(getCard(item.cardId), segment)); return chooseLowest(affinity.length ? affinity : playable, (item) => lineScore(item, state, segment, 'balanced'))?.instanceId ?? null; } };
export function createRandomBot(random = Math.random) { return { name: 'random', chooseMulligan() { return null; }, chooseUtility({ hand }) { const choices = [null, ...hand.filter((item) => [CARD_TYPES.UTILITY, CARD_TYPES.STRAIN].includes(getCard(item.cardId).type)).map((item) => item.instanceId)]; return choices[Math.floor(random() * choices.length)]; }, chooseDiscard({ hand }) { return hand.length ? hand[Math.floor(random() * hand.length)].instanceId : null; }, chooseLine({ playable }) { return playable.length ? playable[Math.floor(random() * playable.length)].instanceId : null; } }; }
