import { CARD_TYPES, SEGMENT_TAGS, SYSTEMS, TIMINGS } from './constants.js';

function card(definition) {
  return Object.freeze({ copies: 1, affinity: [], timeDelta: 0, control: 0, wear: {}, text: '', ...definition });
}

export const CARDS = Object.freeze({
  SAFE_LINE: card({ id: 'safe-line', name: 'Safe Line', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: ['any'], timeDelta: 0.6, control: 2, text: 'Always available. A conservative fallback that prevents a bricked hand.' }),
  SMOOTH_INPUTS: card({ id: 'smooth-inputs', name: 'Smooth Inputs', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: ['any'], timeDelta: -0.7, control: 2, text: 'Stable and repeatable. Builds Flow on a clean on-affinity segment.' }),
  THRESHOLD_BRAKE: card({ id: 'threshold-brake', name: 'Threshold Brake', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.BRAKING, SEGMENT_TAGS.TIGHT], timeDelta: -1.25, control: 1, wear: { [SYSTEMS.BRAKES]: 2, [SYSTEMS.TIRES]: 1 }, text: 'Brake hard in a straight line, release progressively, and arrive at turn-in under control.' }),
  BALANCE_THROTTLE: card({ id: 'balance-throttle', name: 'Balance Throttle', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.FLOWING, SEGMENT_TAGS.TRANSITION], timeDelta: -1.15, control: 1, wear: { [SYSTEMS.TIRES]: 1 }, text: 'Use maintenance throttle and measured weight transfer through a flowing element.' }),
  ROTATE_AND_EXIT: card({ id: 'rotate-and-exit', name: 'Rotate and Exit', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.TIGHT, SEGMENT_TAGS.BRAKING], timeDelta: -1.25, control: 1, wear: { [SYSTEMS.BRAKES]: 1, [SYSTEMS.TIRES]: 1 }, text: 'Finish rotation, unwind the wheel, and feed throttle as the exit opens.' }),
  CLEAN_LAUNCH: card({ id: 'clean-launch', name: 'Clean Launch', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.START, SEGMENT_TAGS.POWER], timeDelta: -1.05, control: 1, wear: { [SYSTEMS.TRANSMISSION]: 1, [SYSTEMS.TIRES]: 1 }, text: 'Launch at the edge of available grip without excessive wheelspin.' }),
  STRAIGHTEN_COURSE: card({ id: 'straighten-course', name: 'Straighten the Course', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.TRANSITION, SEGMENT_TAGS.PRECISION, SEGMENT_TAGS.COMPLEX], timeDelta: -1.2, control: 2, wear: { [SYSTEMS.TIRES]: 1 }, text: 'Connect gates and offsets to reduce steering angle and distance traveled.' }),
  EYES_UP: card({ id: 'eyes-up', name: 'Eyes Up', type: CARD_TYPES.UTILITY, timing: TIMINGS.PRE_LINE, text: 'Draw 2 cards, then discard 1. Play before choosing the Line card.', effect: { draw: 2, discard: 1 } }),
  LATE_BRAKE: card({ id: 'late-brake', name: 'Late Brake', type: CARD_TYPES.AGGRESSION, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.BRAKING, SEGMENT_TAGS.TIGHT], timeDelta: -1.9, control: -1, wear: { [SYSTEMS.BRAKES]: 4, [SYSTEMS.TIRES]: 1 }, text: 'Large immediate gain. Add 1 Unsettled directly to the hand.', effect: { addStrainToHand: 1, breaksFlow: true } }),
  CARRY_ENTRY_SPEED: card({ id: 'carry-entry-speed', name: 'Carry Entry Speed', type: CARD_TYPES.AGGRESSION, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.FLOWING, SEGMENT_TAGS.TRANSITION, SEGMENT_TAGS.PRECISION], timeDelta: -1.85, control: -1, wear: { [SYSTEMS.TIRES]: 3 }, text: 'Commit to a higher entry speed. Add 1 Unsettled directly to the hand.', effect: { addStrainToHand: 1, breaksFlow: true } }),
  FULL_SEND_LAUNCH: card({ id: 'full-send-launch', name: 'Full Send Launch', type: CARD_TYPES.AGGRESSION, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.START, SEGMENT_TAGS.POWER], timeDelta: -1.7, control: -1, wear: { [SYSTEMS.ENGINE]: 3, [SYSTEMS.TRANSMISSION]: 3, [SYSTEMS.TIRES]: 1 }, text: 'Maximum launch commitment. Add 1 Unsettled directly to the hand.', effect: { addStrainToHand: 1, breaksFlow: true } }),
  UNSETTLED: card({ id: 'unsettled', name: 'Unsettled', type: CARD_TYPES.STRAIN, timing: TIMINGS.PASSIVE, text: 'Clogs the hand. Each copy in hand at segment start adds a nonlinear time penalty. Discard one as the Utility play.' }),
  COURSE_CONFUSION: card({ id: 'course-confusion', name: 'Course Confusion', type: CARD_TYPES.HAZARD, timing: TIMINGS.PASSIVE, system: 'course-notes', firesOn: [SEGMENT_TAGS.COMPLEX], text: 'If this fires without a Course Note token, the run is scored DNF.', effect: { dnfUnlessCourseNote: true } }),
  LONG_PEDAL: card({ id: 'long-pedal', name: 'Long Pedal', type: CARD_TYPES.HAZARD, timing: TIMINGS.PASSIVE, system: SYSTEMS.BRAKES, firesOn: [SEGMENT_TAGS.BRAKING], text: 'Poor brake condition increases stopping distance and confidence loss.', effect: { timePenalty: 1.3, controlPenalty: 1, wear: { [SYSTEMS.BRAKES]: 3 } } }),
  GRIP_MISMATCH: card({ id: 'grip-mismatch', name: 'Grip Mismatch', type: CARD_TYPES.HAZARD, timing: TIMINGS.PASSIVE, system: SYSTEMS.TIRES, firesOn: [SEGMENT_TAGS.TIGHT, SEGMENT_TAGS.FLOWING, SEGMENT_TAGS.TRANSITION, SEGMENT_TAGS.PRECISION], text: 'Pressure, temperature, or condition is outside the useful window.', effect: { timePenalty: 1.1, controlPenalty: 1, wear: { [SYSTEMS.TIRES]: 3 } } }),
  HEAT_SOAK: card({ id: 'heat-soak', name: 'Heat Soak', type: CARD_TYPES.HAZARD, timing: TIMINGS.PASSIVE, system: SYSTEMS.ENGINE, firesOn: [SEGMENT_TAGS.POWER, SEGMENT_TAGS.START, SEGMENT_TAGS.FINISH], text: 'Neglected cooling or repeated hot runs reduce power response.', effect: { timePenalty: 1.0, controlPenalty: 0, wear: { [SYSTEMS.ENGINE]: 3 } } }),
  MISSED_SHIFT: card({ id: 'missed-shift', name: 'Missed Shift', type: CARD_TYPES.HAZARD, timing: TIMINGS.PASSIVE, system: SYSTEMS.TRANSMISSION, firesOn: [SEGMENT_TAGS.START, SEGMENT_TAGS.POWER, SEGMENT_TAGS.TRANSITION], text: 'A worn or poorly managed drivetrain costs acceleration and rhythm.', effect: { timePenalty: 1.2, controlPenalty: 1, wear: { [SYSTEMS.TRANSMISSION]: 3 } } }),
  MOMENTUM_DANCE: card({ id: 'momentum-dance', name: 'Momentum Dance', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.TIGHT, SEGMENT_TAGS.FLOWING, SEGMENT_TAGS.TRANSITION], timeDelta: -1.4, control: 2, wear: { [SYSTEMS.TIRES]: 1 }, text: 'Miata identity card: preserve speed through transitions.' }),
  VTEC_WINDOW: card({ id: 'vtec-window', name: 'VTEC Window', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.POWER, SEGMENT_TAGS.FLOWING, SEGMENT_TAGS.FINISH], timeDelta: -1.4, control: 1, wear: { [SYSTEMS.ENGINE]: 2 }, text: 'Integra identity card: keep the engine in its useful power band.' }),
  NEUTRAL_BALANCE: card({ id: 'neutral-balance', name: 'Neutral Balance', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: ['any'], timeDelta: -0.85, control: 2, text: 'Integra identity card: predictable response across varied element types.' }),
  BIG_POWER: card({ id: 'big-power', name: 'Big Power', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.START, SEGMENT_TAGS.POWER, SEGMENT_TAGS.FINISH, SEGMENT_TAGS.FLOWING], timeDelta: -1.6, control: 0, wear: { [SYSTEMS.TIRES]: 2, [SYSTEMS.ENGINE]: 1 }, text: 'Corvette identity card: trade tire demand for strong acceleration and exit speed.' }),
  BREATHE: card({ id: 'breathe', name: 'Breathe', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.START, SEGMENT_TAGS.POWER, SEGMENT_TAGS.FINISH], timeDelta: -1.2, control: 1, wear: { [SYSTEMS.ENGINE]: 1 }, text: 'Stage 1 engine package.' }),
  UPGRADED_THRESHOLD: card({ id: 'upgraded-threshold', name: 'Upgraded Threshold', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.BRAKING, SEGMENT_TAGS.TIGHT], timeDelta: -1.35, control: 2, wear: { [SYSTEMS.BRAKES]: 1, [SYSTEMS.TIRES]: 1 }, text: 'Pads and lines improve modulation and repeatability.' }),
  SET_THE_PLATFORM: card({ id: 'set-the-platform', name: 'Set the Platform', type: CARD_TYPES.TECHNIQUE, timing: TIMINGS.LINE, affinity: [SEGMENT_TAGS.TRANSITION, SEGMENT_TAGS.FLOWING, SEGMENT_TAGS.PRECISION], timeDelta: -1.25, control: 2, wear: { [SYSTEMS.TIRES]: 1 }, text: 'Settle the chassis before the next direction change.', effect: { protectFlowFromHazard: true } }),
  GRIP_WINDOW: card({ id: 'grip-window', name: 'Grip Window', type: CARD_TYPES.UTILITY, timing: TIMINGS.PRE_LINE, text: 'The next Line gains -0.1s and pays half tire wear. Draw 1, then discard 1.', effect: { nextLineTime: -0.1, tireWearMultiplier: 0.5, draw: 1, discard: 1 } }),
});

export const BASE_AUTOCROSS_DECK = Object.freeze([
  'smooth-inputs', 'smooth-inputs', 'threshold-brake', 'threshold-brake',
  'balance-throttle', 'balance-throttle', 'rotate-and-exit', 'rotate-and-exit',
  'clean-launch', 'straighten-course', 'late-brake', 'carry-entry-speed', 'eyes-up', 'eyes-up',
]);

export const CARD_BY_ID = Object.freeze(Object.fromEntries(Object.values(CARDS).map((definition) => [definition.id, definition])));
export function getCard(cardId) { const result = CARD_BY_ID[cardId]; if (!result) throw new Error(`Unknown card: ${cardId}`); return result; }
